### ISSUE TITLE
CSPAbilitySummary/ch19_summary exception

### ISSUE THREAD

**Issue by dstang2000** [CSLearning4U/StudentCSP#20]
when I use "runestone build" command, I get the error msg: 

writing output... [  0%] CSPAbilitySummary/ch19_summary                         
Exception occurred:
  File "/usr/local/lib/python3.6/site-packages/sphinx/util/osutil.py", line 61, in relative_uri
    if to.startswith(SEP):
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'filename'
The full traceback has been saved in /tmp/sphinx-err-wsjiah5b.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
trying alternative database access due to  No module named 'dal'
You need to install a DBAPI module - psycopg2 for Postgres
Creating Chapter Information for _sources/index.rst
Error in building StudentCSP

**Comment by katieirenec** [comment]
Hi @dstang2000!

I am getting a successful build with `runestone build` on my machine. 

Can you tell us more about how you installed runestone? I'm thinking that perhaps you might be missing a library.

**Comment by ericsonga** [comment]
You might need to install psycopg2 (pip install psycopg2)

**Comment by TangDashi** [comment]
Thank you, katierenec and ericsonga.
I installed postgresql and related lib, it works!

**Comment by katieirenec** [comment]
Excellent! Glad to hear it :)
