### ISSUE TITLE
Missing link to assignments

### ISSUE THREAD

**Issue by bnmnetp** [CSLearning4U/StudentCSP#21]
The index.rst file for the StudentCSP (all base courses for that matter) book should have a link to assignments.html on the main TOC page.

At the moment I just have this in thinkcspy:

```
.. raw:: html

   <ul>
   <li><a href="assignments.html">Assignments</a></li>
   </ul>
```

Once the new interface goes live, it will be:

```
.. raw:: html

   <ul>
   <li><a href="/runestone/assignments/chooseAssignment.html">Assignments</a></li>
   </ul>
```

**Comment by ericsonga** [comment]
I added this.
